language: php

php:
  - 7.1
  - 7.0
  - 5.6

install:
 - composer install --dev --no-interaction

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
